# WEB INTERFACE Dockerfile

# Milestone 4.5: Containernes Dockerfiler skal være basert på egendefinert bilde
FROM cgi-image:base
WORKDIR ./

# COPY over necessary files to cgi-bin
COPY ./index.cgi ./index.html /usr/local/apache2/cgi-bin/
