version: '3.8'

# Milestone 4.6: Funksjonell docker-compose-fil for start og stopp av konteiner
services:
  webinterface:
    build:
      context: ./webinterface
      dockerfile: Dockerfile
    ports:
      - "8180:80"
    deploy:
# Milestone 4.1: Prosessorbruken til containeren skal begrenses med cgroups
      resources:
        limits:
          cpus: '0.5'
# Milestone 4.2: Sikkerheten skal økes ved hjelp av capabilities
    cap_drop:
      - ALL
    cap_add:
      - SYS_TIME
      - CAP_SETUID
      - CAP_SETGID
      - CAP_NET_ADMIN
      - CAP_SYS_ADMIN
    extra_hosts:
      - "host.docker.internal:host-gateway"

  restapi:
    build:
      context: ./restapi
      dockerfile: Dockerfile
    ports:
      - "8280:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
    cap_drop:
      - ALL
    cap_add:
      - SYS_TIME
      - CAP_SETUID
      - CAP_SETGID
      - CAP_NET_ADMIN
      - CAP_SYS_ADMIN
    extra_hosts:
      - "host.docker.internal:host-gateway"
