version: '3.8'

services:
  webinterface:
    build:
      context: ./webinterface
      dockerfile: Dockerfile
    ports:
      - "8180:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
    cap_drop:
      - ALL
    cap_add:
      - SYS_TIME
      - CAP_SETUID
      - CAP_SETGID
      - CAP_NET_ADMIN
      - CAP_SYS_ADMIN
    extra_hosts:
      - "host.docker.internal:host-gateway"

  restapi:
    build:
      context: ./restapi
      dockerfile: Dockerfile
    ports:
      - "8280:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
    cap_drop:
      - ALL
    cap_add:
      - SYS_TIME
      - CAP_SETUID
      - CAP_SETGID
      - CAP_NET_ADMIN
      - CAP_SYS_ADMIN
    extra_hosts:
      - "host.docker.internal:host-gateway"
